### ISSUE TITLE
重载的时候开始闪退

### ISSUE THREAD

**Issue by yingnierxiao** [cloudwu/skynet-reload#1]
[:00000010] Version 0
true    0
true    1
true    2
true    3
gamestart.sh: line 18:  6623 Segmentation fault: 11 

Thread 7 Crashed:
0   skynet                          0x000000010382d96e lua_gc + 30
1   reload.so                       0x00000001040e35e0 lreload + 144 (lua-reload.c:118)
2   skynet                          0x000000010383255c luaD_precall + 780
3   skynet                          0x0000000103842e90 luaV_execute + 3376
4   skynet                          0x0000000103831e19 luaD_rawrunprotected + 89
5   skynet                          0x0000000103832e03 lua_resume + 83
6   skynet                          0x0000000103848f22 auxresume + 82
7   skynet                          0x0000000103848ca9 luaB_coresume + 73
8   profile.so                      0x00000001040bbba4 timing_resume + 180 (lua-profile.c:131)
9   skynet                          0x000000010383255c luaD_precall + 780
10  skynet                          0x0000000103842e90 luaV_execute + 3376
11  skynet                          0x0000000103832d7c luaD_callnoyield + 76
12  skynet                          0x0000000103831e19 luaD_rawrunprotected + 89
13  skynet                          0x00000001038332c4 luaD_pcall + 68
14  skynet                          0x000000010382d414 lua_pcallk + 212
15  skynet                          0x00000001038482a6 luaB_pcall + 86
16  skynet                          0x000000010383255c luaD_precall + 780
17  skynet                          0x0000000103842e90 luaV_execute + 3376
18  skynet                          0x0000000103832d7c luaD_callnoyield + 76
19  skynet                          0x0000000103831e19 luaD_rawrunprotected + 89
20  skynet                          0x00000001038332c4 luaD_pcall + 68
21  skynet                          0x000000010382d414 lua_pcallk + 212
22  skynet.so                       0x00000001040b4587 _cb + 199 (lua-skynet.c:50)
23  skynet                          0x0000000103823f7f dispatch_message + 143 (skynet_server.c:259)
24  skynet                          0x00000001038240a2 skynet_context_message_dispatch + 210 (skynet_server.c:313)
25  skynet                          0x0000000103825a3e thread_worker + 94 (skynet_start.c:163)
26  libsystem_pthread.dylib         0x00007fff9e28399d _pthread_body + 131
27  libsystem_pthread.dylib         0x00007fff9e28391a _pthread_start + 168
28  libsystem_pthread.dylib         0x00007fff9e281351 thread_start + 13

**Comment by cloudwu** [comment]
需要测试案例。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet-reload/commit/fc04dc46cc4d42f4de44e13752b3cda8f5505daf  skynet 的 C api 有变更。

看看是不是这个造成的。

不过按理说，这个库应该和目前的 skynet 版本一起编译会有 warning 的呀？你构建项目忽略警告？

**Comment by yingnierxiao** [comment]
是有警告 。。我忽视了。。
