### ISSUE TITLE
简单测试reload不成功

### ISSUE THREAD

**Issue by mayao11** [cloudwu/skynet-reload#3]
只是简单运行test里的例子，然后运行中修改echo_reload.lua，保存
把echo_reload.lua中的
skynet.ret(skynet.pack("==--", msg))
改为
skynet.ret(skynet.pack("==", msg.." "..version))

下次加载时，运行效果并没有改变

**Comment by cloudwu** [comment]
RTFM https://github.com/cloudwu/skynet/wiki/CodeCache
